### PR TITLE
#164611280 Add categories on article

### PR DESCRIPTION
**Pull request by niomwungeri-fabrice**
#### What does this PR do?
- add categories on 
landing page using HTML and CSS
#### Description of Task to be completed?
- Create the HTML and CSS page
- Make it responsive for both mobile and desktop
#### How should this be manually tested?
- Fetch origin
- Check out the branch ft-add-categories-on-article-164611280
- Open the following file pages/landing.html in chrome or firefox
- And use the inspector to view the page with different devices.
#### Any background context you want to provide?
None
#### What are the relevant pivotal tracker stories?
 - #164611280
#### Screenshots (if appropriate):
- Desktop Version
Screen Shot 2019-03-14 at 16 08 55
- Mobile version
Screen Shot 2019-03-14 at 16 09 53

#### Questions:
None

### CODE REVIEW

**Review by oesukam — CHANGES_REQUESTED** [review]
@niomwungeri-fabrice 
The last item of categories should have a different look to give users a hint that it is clickable
image

The horizontal should be hidden because it is overlaying the content and also doesn't make the content look nice
image

**Review by abayo-luc — CHANGES_REQUESTED** [review]
how about fixing categories fixed at the top as a user scroll down. It would make it easier for them to navigate through our app. What do you think?

**Comment by niomwungeri-fabrice** [comment]
> how about fixing categories fixed at the top as a user scroll down. It would make it easier for them to navigate through our app. What do you think?

@abayo-luc It's a great idea, I have implemented it. Thanks

**Review by abayo-luc — APPROVED** [review]

**Review by Musigwa-zz — APPROVED** [review]
You can rebase and resolve the rebase conflicts. Other than that, the work looks great.

**Pull request merged**
