### PR TITLE
#163518639 setup react router for the application

### PR DESCRIPTION
**Pull request by espoirMur**
#### What does this PR do?
Setup react router version for the application
#### Description of Task to be completed?
- Setup react router for the application
- Create a route to the homepage
- Create a route to the login page
- Create a route for 404 errors pages
#### How should this be manually tested?
- clone the repo and check out the following branch `ch-setup-react-router-version-163518639`
- run `yarn start` and navigate to /home , / , or /login in your browser
-  try to open any other URL you want to check if the 404 page is working
#### Any background context you want to provide?
None
#### What are the relevant pivotal tracker stories?
#163518639
#### Screenshots (if appropriate)
None
#### Questions:

### CODE REVIEW

**Review by abayo-luc — APPROVED** [review]

**Review by Musigwa-zz — CHANGES_REQUESTED** [review]
The whole work looks great with the detailed description that guided me until the last point of manual testing. @espoirMur I've got to ask you some a sort of questions:

1.  Would it be a bad idea to ignore the [.DS_Store](http://osxdaily.com/2009/12/31/what-is-a-ds_store-file/) and [yarn.lock](https://yarnpkg.com/lang/en/docs/yarn-lock/) file? 
2. Will the not found page be designed right after by someone else or you can complete it within this PR?

Looking forward to hearing from you.

**Comment by espoirMur** [comment]
Thanks  @musigwa for this piece of feedback!

1.  from wikipedia I just found that  
>  In the Apple macOS operating system, .DS_Store is a file that stores custom attributes of its containing folder, such as the position of icons or the choice of a background image. The name is an abbreviation of Desktop Services Store,reflecting its purpose.
Since the .DS_Store file is specific to my laptop there is no change to keep in git and that is the reason why I have ignored it. 

For the yarn.lock file I think it's for the team convention from the last repo..
2. the not found page is just a template , the final page should be design by someone else .

**Review by Musigwa-zz — APPROVED** [review]

**Review by abayo-luc — APPROVED** [review]
Fix HoundCI

**Review by abayo-luc — CHANGES_REQUESTED** [review]
Fix houndCI

**Pull request closed without merging**
