### PR TITLE
163518638 Configure TravisCI

### PR DESCRIPTION
**Pull request by niomwungeri-fabrice**
#### What does this PR do?
This PR sets up the TravisCI and simple test
#### Description of Task to be completed?
* We created the`.travis.yml` file that contains every configuration required.
#### How should this be manually tested
* Visit travis-ci.org 
* Click the button to sign in with Github. 
* Give Travis CI access to your account. 
* You can specify exactly which repositories Travis CI should be given access to.
* From there it will be either `Red Color` to indicate The failure or The `Green color` to indicate the success of integration between the project and TravisCI

#### Any background context you want to provide?
None  
#### What are the relevant pivotal tracker stories?
#163518638 
#### Questions:
None

### CODE REVIEW

**Comment by Musigwa-zz** [comment]
> #### What does this PR do?
> This PR sets up the TravisCI and simple test
> 
> #### Description of Task to be completed?
> * We created the`.travis.yml` file that contains every configuration required.
> 
> #### How should this be manually tested
> Visit [travisCI](https://travis-ci.com/andela/titan-dev-ah-frontend)
> 
> #### Any background context you want to provide?
> None
> 
> #### What are the relevant pivotal tracker stories?
> #163518638
> 
> #### Questions:
> None

It seems like the description is not complete. You said to visit  [travisCI](https://travis-ci.com/andela/titan-dev-ah-frontend), but what to do while there?

**Comment by niomwungeri-fabrice** [comment]
> > #### What does this PR do?
> > This PR sets up the TravisCI and simple test
> > #### Description of Task to be completed?
> > 
> > * We created the`.travis.yml` file that contains every configuration required.
> > 
> > #### How should this be manually tested
> > Visit [travisCI](https://travis-ci.com/andela/titan-dev-ah-frontend)
> > #### Any background context you want to provide?
> > None
> > #### What are the relevant pivotal tracker stories?
> > #163518638
> > #### Questions:
> > None
> 
> It seems like the description is not complete. You said to visit [travisCI](https://travis-ci.com/andela/titan-dev-ah-frontend), but what to do while there?

Hi @Musigwa, 

Testing how the project is configured with Travis, otherwise, nothing would be there.

Thanks!

**Review by Musigwa-zz — CHANGES_REQUESTED** [review]
@niomwungeri-fabrice, will you mind to rewrite how this can be manually tested to make it meaningful?

**Comment by niomwungeri-fabrice** [comment]
> @niomwungeri-fabrice, will you mind to rewrite how this can be manually tested to make it meaningful?



> #### What does this PR do?
> This PR sets up the TravisCI and simple test
> 
> #### Description of Task to be completed?
> * We created the`.travis.yml` file that contains every configuration required.
> 
> #### How should this be manually tested
> Visit [travisCI](https://travis-ci.com/andela/titan-dev-ah-frontend)
> 
> #### Any background context you want to provide?
> None
> 
> #### What are the relevant pivotal tracker stories?
> #163518638
> 
> #### Questions:
> None



> @niomwungeri-fabrice, will you mind to rewrite how this can be manually tested to make it meaningful?

> @Musigwa, Can you check again and let me know what you think?

**Review by espoirMur — APPROVED** [review]
LGTM

**Review by Musigwa-zz — APPROVED** [review]
Looks good with detailed description. Keep it up @niomwungeri-fabrice

**Pull request merged**
