### PR TITLE
16452841 View more category page

### PR DESCRIPTION
**Pull request by niomwungeri-fabrice**
#### What does this PR do?
- add view more category page  
#### Description of Task to be completed?
- Create the HTML and CSS page
- Make it responsive for both mobile and desktop
#### How should this be manually tested?
- Fetch origin
- Checkout the branch ft-view-more-category-16452841
- Open the following file pages/more-category.html in chrome or firefox
- And use the inspector to view the page with different devices.
#### Any background context you want to provide?
None
#### What are the relevant pivotal tracker stories?
 - #164611280
#### Screenshots (if appropriate):
- Mobile version
Screen Shot 2019-03-14 at 13 05 22
- Desktop Version
Screen Shot 2019-03-14 at 13 05 40

### CODE REVIEW

**Review by abayo-luc — CHANGES_REQUESTED** [review]
- Make your card clickable.

**Review by YvesIraguha — APPROVED** [review]
Apply feedback, and resolve conflicts in the mentioned files.

**Comment by niomwungeri-fabrice** [comment]
> * Make your card clickable.

Yes, I have @abayo-luc. Thanks

**Comment by niomwungeri-fabrice** [comment]
> Apply feedback, and resolve conflicts in the mentioned files.

Done! 
Thanks. @YvesIraguha

**Review by abayo-luc — APPROVED** [review]

**Pull request merged**
